#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/virtlogd" ] ; then
	chmod +x "/etc/init.d/virtlogd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/libvirtd" ] ; then
	chmod +x "/etc/init.d/libvirtd" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/libvirt-guests" ] ; then
	chmod +x "/etc/init.d/libvirt-guests" >/dev/null || true
fi
# End automatically added section
